# Generated by Django 2.2.4 on 2021-11-05 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSoils',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landscapeId', models.CharField(max_length=200, verbose_name='地理编号')),
                ('soilId', models.CharField(max_length=200, verbose_name='土种编号')),
                ('groupId', models.CharField(max_length=200, verbose_name='组别编号')),
                ('subgroupId', models.CharField(max_length=200, verbose_name='区域编号')),
                ('soilTypeName', models.CharField(max_length=50, verbose_name='土种名称')),
                ('profileSamplingLocation', models.CharField(max_length=100, verbose_name='典型剖面采集地点')),
                ('profileGromorph', models.TextField(max_length=2000, verbose_name='典型剖面地形地貌和部位')),
                ('profileElevation', models.CharField(max_length=200, verbose_name='典型剖面高程')),
                ('profileParent', models.TextField(max_length=200, verbose_name='典型剖面母质')),
                ('annualTemperature', models.CharField(max_length=200, verbose_name='典型剖面地点年均温')),
                ('annualPrecipitation', models.CharField(max_length=200, verbose_name='典型剖面年降水')),
                ('accumTemp', models.CharField(max_length=200, verbose_name='>10℃积温')),
                ('frostFreePeriod', models.CharField(max_length=100, verbose_name='无霜期')),
                ('profileVegetation', models.TextField(max_length=500, verbose_name='自然植被')),
                ('profileLanduse', models.TextField(max_length=500, verbose_name='土地利用')),
            ],
            options={
                'verbose_name': '区域土壤信息',
                'verbose_name_plural': '区域土壤信息',
            },
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Whether_helps', models.CharField(max_length=30, verbose_name='设计方案是否有帮助')),
                ('Detailed', models.CharField(max_length=30, verbose_name='设计方案是否详细')),
                ('Humanize', models.CharField(max_length=30, verbose_name='网站设计是否足够人性化')),
                ('Provide', models.CharField(max_length=80, verbose_name='还需要提供什么服务功能')),
                ('Other', models.TextField(verbose_name='其他想法')),
            ],
        ),
        migrations.CreateModel(
            name='Liaison_cooperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=30, verbose_name='客户姓名')),
                ('Company_name', models.CharField(max_length=30, verbose_name='单位名称')),
                ('Telephone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('Types_section', models.CharField(max_length=15, verbose_name='合作类型')),
                ('Project_description', models.TextField(verbose_name='项目描述')),
            ],
        ),
        migrations.CreateModel(
            name='NewType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeedMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mesogastropoda', models.CharField(max_length=50, verbose_name='中文科名')),
                ('Littorinidae', models.CharField(max_length=50, verbose_name='中文属名')),
                ('anotherName', models.CharField(max_length=50, verbose_name='别名')),
                ('morphological', models.TextField(max_length=1500, verbose_name='形态特征')),
                ('Geographic', models.TextField(max_length=1500, verbose_name='地理环境及基本生长环境')),
                ('EdibleParts', models.TextField(max_length=50, verbose_name='食用部位')),
                ('seedProductionTechnique', models.TextField(max_length=1500, verbose_name='制种技术')),
                ('seedMorphological', models.TextField(max_length=1500, verbose_name='种子形态')),
                ('germination', models.TextField(max_length=1500, verbose_name='萌发条件')),
                ('drying', models.TextField(max_length=1500, verbose_name='干燥条件')),
                ('StorageAndLife', models.TextField(max_length=1500, verbose_name='储藏和寿命')),
                ('processingMethod', models.TextField(max_length=5100, verbose_name='加工方法')),
                ('identificationMethods', models.TextField(max_length=1500, verbose_name='质量检测和简易鉴别方法')),
                ('SowingPeriod', models.TextField(max_length=1500, verbose_name='播种期、生长期')),
                ('cultivationMeasure', models.TextField(max_length=1500, verbose_name='栽培措施')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
            ],
            options={
                'verbose_name': '种子',
                'verbose_name_plural': '种子',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='SoilMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soilName', models.CharField(max_length=50, verbose_name='土类名称')),
                ('soilEngName', models.CharField(max_length=50, verbose_name='土类英文名')),
                ('soilClassName', models.CharField(max_length=50, verbose_name='土纲名称')),
                ('soilClassEngName', models.CharField(max_length=50, verbose_name='土纲英文名')),
                ('soilDescription', models.TextField(max_length=5000, verbose_name='土类描述')),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
            ],
            options={
                'verbose_name': '土类信息',
                'verbose_name_plural': '土类信息',
                'ordering': ['-createdTime'],
            },
        ),
        migrations.CreateModel(
            name='SubClassMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subClassName', models.CharField(max_length=50, verbose_name='亚类名称')),
                ('subClassEngName', models.CharField(max_length=50, verbose_name='亚类英文名')),
                ('subClassNatName', models.CharField(max_length=50, verbose_name='亚类国标名')),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('subgroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BNX_Website.SoilMess')),
            ],
            options={
                'verbose_name': '亚类信息',
                'verbose_name_plural': '亚类信息',
                'ordering': ['-createdTime'],
            },
        ),
        migrations.CreateModel(
            name='SoilSeedMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soilSeedName', models.CharField(max_length=50, verbose_name='土种名称')),
                ('soilSeedDescript', models.TextField(max_length=2000, verbose_name='描述')),
                ('distributionLandform', models.TextField(max_length=2000, verbose_name='分布和地形地貌')),
                ('areaHectare', models.CharField(max_length=50, verbose_name='面积（公顷）')),
                ('areaMu', models.CharField(max_length=50, verbose_name='面积（万亩）')),
                ('material', models.TextField(max_length=2000, verbose_name='母质')),
                ('configuration', models.TextField(max_length=2000, verbose_name='剖面构型')),
                ('effectSoilDepth', models.TextField(max_length=2000, verbose_name='有效土体深度')),
                ('mainCharacters', models.TextField(max_length=2000, verbose_name='主要性状')),
                ('barrierFactor', models.TextField(max_length=2000, verbose_name='土壤障碍因子')),
                ('productPerformance', models.TextField(max_length=2000, verbose_name='生产性能')),
                ('landUse', models.TextField(max_length=2000, verbose_name='土地利用')),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('soilSeedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BNX_Website.SubClassMess')),
            ],
            options={
                'verbose_name': '土种信息',
                'verbose_name_plural': '土种信息',
                'ordering': ['-createdTime'],
            },
        ),
        migrations.CreateModel(
            name='seedImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='种子图片')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seedImgs', to='BNX_Website.SeedMess', verbose_name='种子')),
            ],
            options={
                'verbose_name': '种子图片',
                'verbose_name_plural': '种子图片',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='图片')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('quote', models.TextField(blank=True, default='', verbose_name='引用')),
                ('url', models.URLField(blank=True, verbose_name='引用链接')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='新闻作者')),
                ('new_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BNX_Website.NewType', verbose_name='新闻类型')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
