# Generated by Django 2.2.4 on 2021-11-05 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BNX_Website', '0002_auto_20211105_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSoils',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landscapeId', models.CharField(max_length=200, verbose_name='地理编号')),
                ('soilId', models.CharField(max_length=200, verbose_name='土种编号')),
                ('groupId', models.CharField(max_length=200, verbose_name='组别编号')),
                ('subgroupId', models.CharField(max_length=200, verbose_name='区域编号')),
                ('soilTypeName', models.CharField(max_length=50, verbose_name='土种名称')),
                ('profileSamplingLocation', models.CharField(max_length=100, verbose_name='典型剖面采集地点')),
                ('profileGromorph', models.TextField(max_length=2000, verbose_name='典型剖面地形地貌和部位')),
                ('profileElevation', models.CharField(max_length=200, verbose_name='典型剖面高程')),
                ('profileParent', models.TextField(max_length=200, verbose_name='典型剖面母质')),
                ('annualTemperature', models.CharField(max_length=200, verbose_name='典型剖面地点年均温')),
                ('annualPrecipitation', models.CharField(max_length=200, verbose_name='典型剖面年降水')),
                ('accumTemp', models.CharField(max_length=200, verbose_name='>10℃积温')),
                ('frostFreePeriod', models.CharField(max_length=100, verbose_name='无霜期')),
                ('profileVegetation', models.TextField(max_length=500, verbose_name='自然植被')),
                ('profileLanduse', models.TextField(max_length=500, verbose_name='土地利用')),
            ],
            options={
                'verbose_name': '区域土壤信息',
                'verbose_name_plural': '区域土壤信息',
            },
        ),
        migrations.CreateModel(
            name='SubClassMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subClassName', models.CharField(max_length=50, verbose_name='亚类名称')),
                ('subClassEngName', models.CharField(max_length=50, verbose_name='亚类英文名')),
                ('subClassNatName', models.CharField(max_length=50, verbose_name='亚类国标名')),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('subgroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BNX_Website.SoilMess')),
            ],
            options={
                'verbose_name': '亚类信息',
                'verbose_name_plural': '亚类信息',
                'ordering': ['-createdTime'],
            },
        ),
        migrations.CreateModel(
            name='SoilSeedMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soilSeedName', models.CharField(max_length=50, verbose_name='土种名称')),
                ('soilSeedDescript', models.TextField(max_length=2000, verbose_name='描述')),
                ('distributionLandform', models.TextField(max_length=2000, verbose_name='分布和地形地貌')),
                ('areaHectare', models.CharField(max_length=50, verbose_name='面积（公顷）')),
                ('areaMu', models.CharField(max_length=50, verbose_name='面积（万亩）')),
                ('material', models.TextField(max_length=2000, verbose_name='母质')),
                ('configuration', models.TextField(max_length=2000, verbose_name='剖面构型')),
                ('effectSoilDepth', models.TextField(max_length=2000, verbose_name='有效土体深度')),
                ('mainCharacters', models.TextField(max_length=2000, verbose_name='主要性状')),
                ('barrierFactor', models.TextField(max_length=2000, verbose_name='土壤障碍因子')),
                ('productPerformance', models.TextField(max_length=2000, verbose_name='生产性能')),
                ('landUse', models.TextField(max_length=2000, verbose_name='土地利用')),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('soilSeedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BNX_Website.SubClassMess')),
            ],
            options={
                'verbose_name': '土种信息',
                'verbose_name_plural': '土种信息',
                'ordering': ['-createdTime'],
            },
        ),
    ]
