# Generated by Django 2.2.4 on 2021-11-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNX_Website', '0003_areasoils_soilseedmess_subclassmess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaSoils',
        ),
    ]
