# Generated by Django 2.2.4 on 2021-11-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BNX_Website', '0004_delete_areasoils'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSoils',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('landscapeId', models.CharField(max_length=200, verbose_name='地理编号')),
                ('soilId', models.CharField(max_length=200, verbose_name='土种编号')),
                ('groupId', models.CharField(max_length=200, verbose_name='组别编号')),
                ('subgroupId', models.CharField(max_length=200, verbose_name='区域编号')),
                ('soilTypeName', models.CharField(max_length=50, verbose_name='土种名称')),
                ('profileSamplingLocation', models.CharField(max_length=100, verbose_name='典型剖面采集地点')),
                ('profileGromorph', models.TextField(max_length=2000, verbose_name='典型剖面地形地貌和部位')),
                ('profileElevation', models.CharField(max_length=200, verbose_name='典型剖面高程')),
                ('profileParent', models.TextField(max_length=200, verbose_name='典型剖面母质')),
                ('annualTemperature', models.CharField(max_length=200, verbose_name='典型剖面地点年均温')),
                ('annualPrecipitation', models.CharField(max_length=200, verbose_name='典型剖面年降水')),
                ('accumTemp', models.CharField(max_length=200, verbose_name='>10℃积温')),
                ('frostFreePeriod', models.CharField(max_length=100, verbose_name='无霜期')),
                ('profileVegetation', models.TextField(max_length=500, verbose_name='自然植被')),
                ('profileLanduse', models.TextField(max_length=500, verbose_name='土地利用')),
            ],
            options={
                'verbose_name': '区域土壤信息',
                'verbose_name_plural': '区域土壤信息',
            },
        ),
    ]
