# Generated by Django 2.2.4 on 2021-11-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNX_Website', '0005_areasoils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclassmess',
            name='subgroupId',
        ),
        migrations.DeleteModel(
            name='SoilSeedMess',
        ),
        migrations.DeleteModel(
            name='SubClassMess',
        ),
    ]
