# Generated by Django 2.2.4 on 2021-11-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BNX_Website', '0008_auto_20211117_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilmess',
            name='soilClassEngName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='土纲英文名'),
        ),
        migrations.AlterField(
            model_name='soilmess',
            name='soilClassName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='土纲名称'),
        ),
        migrations.AlterField(
            model_name='soilmess',
            name='soilDescription',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='土类描述'),
        ),
        migrations.AlterField(
            model_name='soilmess',
            name='soilEngName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='土类英文名'),
        ),
        migrations.AlterField(
            model_name='soilmess',
            name='soilName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='土类名称'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='areaHectare',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='面积（公顷）'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='areaMu',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='面积（万亩）'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='barrierFactor',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='土壤障碍因子'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='configuration',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='剖面构型'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='distributionLandform',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='分布和地形地貌'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='effectSoilDepth',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='有效土体深度'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='landUse',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='土地利用'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='mainCharacters',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='主要性状'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='material',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='母质'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='productPerformance',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='生产性能'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='soilSeedDescript',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='soilseedmess',
            name='soilSeedName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='土种名称'),
        ),
        migrations.AlterField(
            model_name='subclassmess',
            name='subClassEngName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='亚类英文名'),
        ),
        migrations.AlterField(
            model_name='subclassmess',
            name='subClassName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='亚类名称'),
        ),
        migrations.AlterField(
            model_name='subclassmess',
            name='subClassNatName',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='亚类国标名'),
        ),
    ]
