# Generated by Django 2.2.4 on 2021-11-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNX_Website', '0012_auto_20211117_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilseedmess',
            name='soilSeedId',
        ),
        migrations.RemoveField(
            model_name='subclassmess',
            name='subgroupId',
        ),
        migrations.DeleteModel(
            name='SoilMess',
        ),
        migrations.DeleteModel(
            name='SoilSeedMess',
        ),
        migrations.DeleteModel(
            name='SubClassMess',
        ),
    ]
