# Generated by Django 2.2.4 on 2021-11-18 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BNX_Website', '0013_auto_20211118_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soilName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='土类名称')),
                ('soilEngName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='土类英文名')),
                ('soilClassName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='土纲名称')),
                ('soilClassEngName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='土纲英文名')),
                ('soilDescription', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='土类描述')),
                ('createdTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
            ],
            options={
                'verbose_name': '土类信息',
                'verbose_name_plural': '土类信息',
                'ordering': ['-createdTime'],
            },
        ),
        migrations.CreateModel(
            name='SubClassMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subClassName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='亚类名称')),
                ('subClassEngName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='亚类英文名')),
                ('subClassNatName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='亚类国标名')),
                ('createdTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('subgroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BNX_Website.SoilMess')),
            ],
            options={
                'verbose_name': '亚类信息',
                'verbose_name_plural': '亚类信息',
                'ordering': ['-createdTime'],
            },
        ),
        migrations.CreateModel(
            name='SoilSeedMess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soilSeedName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='土种名称')),
                ('soilSeedDescript', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='描述')),
                ('distributionLandform', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='分布和地形地貌')),
                ('areaHectare', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='面积（公顷）')),
                ('areaMu', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='面积（万亩）')),
                ('material', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='母质')),
                ('configuration', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='剖面构型')),
                ('effectSoilDepth', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='有效土体深度')),
                ('mainCharacters', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='主要性状')),
                ('barrierFactor', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='土壤障碍因子')),
                ('productPerformance', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='生产性能')),
                ('landUse', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='土地利用')),
                ('createdTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('soilSeedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BNX_Website.SubClassMess')),
            ],
            options={
                'verbose_name': '土种信息',
                'verbose_name_plural': '土种信息',
                'ordering': ['-createdTime'],
            },
        ),
    ]
