# Generated by Django 2.2.4 on 2021-11-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BNX_Website', '0014_soilmess_soilseedmess_subclassmess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaSoils',
        ),
    ]
